#load libraries
library(here)
library(dplyr)
library(readr)
library(reshape2)
library(ggplot2)
library(gdata)
library(gtable)
library(RColorBrewer)
library(gridExtra)
library(grid)
library(lattice)
library(vegan)
library(stringr)
library(ggrepel)
library(oce)
library(ggmap)
library(extrafont)
library(corrplot)
library(matrixStats)
library(lubridate)
library(here)
library(patchwork)
library(data.table)
library(janitor)
library(ncdf4)
library(ggnewscale)
library(ggsidekick)
library(cowplot)


#install.packages("ggExtra")
#install.packages("here")
# now()
# here()
#devtools::install_github("thomasp85/patchwork")